export const infoLinks = [
    { title: "Alvará de bombeiro valor", url: "/alvara-bombeiro-valor" },
    { title: "Alvará corpo de bombeiros sp", url: "/alvara-corpo-bombeiros-sp" },
    { title: "Assessoria ambiental para posto de combustível em sp", url: "/assessoria-ambiental-posto-combustivel-sp" },
    { title: "Assessoria ambiental para posto de combustível", url: "/assessoria-ambiental-posto-combustivel" },
    { title: "Assessoria ambiental preço", url: "/assessoria-ambiental-preco" },
    { title: "Assessoria ambiental valor", url: "/assessoria-ambiental-valor" },
    { title: "Assessoria Ambiental", url: "/assessoria-ambiental" },
    { title: "Autorização corte de árvore", url: "/autorizacao-corte-arvore" },
    { title: "Autorização para corte de árvores sp", url: "/autorizacao-corte-arvores-sp" },
    { title: "Cadastro car sp", url: "/cadastro-car-sp" },
    { title: "Car cadastro ambiental rural sp", url: "/car-cadastro-ambiental-rural-sp" },
    { title: "Clcb valor", url: "/clcb-valor" },
    { title: "Consultoria ambiental garagem de ônibus em sp", url: "/consultoria-ambiental-garagem-onibus-sp" },
    { title: "Consultoria ambiental orçamento", url: "/consultoria-ambiental-orcamento" },
    { title: "Consultoria ambiental para posto de combustível", url: "/consultoria-ambiental-posto-combustivel" },
    { title: "Consultoria ambiental preço", url: "/consultoria-ambiental-preco" },
    { title: "Consultoria ambiental são paulo", url: "/consultoria-ambiental-sao-paulo" },
    { title: "Consultoria ambiental valor", url: "/consultoria-ambiental-valor" },
    { title: "Consultoria e assessoria ambiental", url: "/consultoria-assessoria-ambiental" },
    { title: "Contrato prestação de serviço consultoria ambiental", url: "/contrato-prestacao-servico-consultoria-ambiental" },
    { title: "Corte de árvore nativa isolada em ribeirão preto", url: "/corte-arvore-nativa-isolada-ribeirao-preto" },
    { title: "Corte de árvore nativa isolada em são paulo", url: "/corte-arvore-nativa-isolada-sao-paulo" },
    { title: "Corte de Árvore Nativa Isolada", url: "/corte-arvore-nativa-isolada" },
    { title: "Empresa de alvará de bombeiro orçamento ribeirão preto", url: "/empresa-alvara-bombeiro-orcamento-ribeirao-preto" },
    { title: "Empresa de aprovação de corpo de bombeiro", url: "/empresa-aprovacao-corpo-bombeiro" },
    { title: "Empresa de assessoria ambiental para posto de combustível", url: "/empresa-assessoria-ambiental-posto-combustivel" },
    { title: "Empresa de consultoria ambiental", url: "/empresa-consultoria-ambiental" },
    { title: "Empresa de homologação de pátio de madeira", url: "/empresa-homologacao-patio-madeira" },
    { title: "Empresa de licença ambiental fertilizante em sp", url: "/empresa-licenca-ambiental-fertilizante-sp" },
    { title: "Empresa de licença ambiental fertilizante", url: "/empresa-licenca-ambiental-fertilizante" },
    { title: "Empresa de licença ambiental para postos de combustível", url: "/empresa-licenca-ambiental-postos-combustivel" },
    { title: "Empresa de licença ambiental", url: "/empresa-licenca-ambiental" },
    { title: "Empresa de licenciamento ambiental garagem de ônibus", url: "/empresa-licenciamento-ambiental-garagem-onibus" },
    { title: "Empresa de outorga daee em ribeirão preto", url: "/empresa-outorga-daee-ribeirao-preto" },
    { title: "Empresa de outorga daee", url: "/empresa-outorga-daee" },
    { title: "Empresa de projeto de bombeiro avcb", url: "/empresa-projeto-bombeiro-avcb" },
    { title: "Empresa que faz autorização para corte de árvore", url: "/empresa-que-faz-autorizacao-corte-arvore" },
    { title: "Empresa que faz cadastro anp em sp", url: "/empresa-que-faz-cadastro-anp-sp" },
    { title: "Empresa que faz cadastro anp", url: "/empresa-que-faz-cadastro-anp" },
    { title: "Empresa que faz cadastro ibama", url: "/empresa-que-faz-cadastro-ibama" },
    { title: "Empresa que faz licenciamento ambiental de fertilizante", url: "/empresa-que-faz-licenciamento-ambiental-fertilizante" },
    { title: "Empresa que faz solicitação de outorga", url: "/empresa-que-faz-solicitacao-outorga" },
    { title: "Empresa de regularização ambiental posto de combustível", url: "/empresa-regularizacao-ambiental-posto-combustivel" },
    { title: "Empresas de estudos ambientais", url: "/empresas-estudos-ambientais" },
    { title: "Georreferenciamento rural preço", url: "/georreferenciamento-rural-preco" },
    { title: "Gerenciamento ambiental de áreas contaminadas", url: "/gerenciamento-ambiental-areas-contaminadas" },
    { title: "Gerenciamento de áreas contaminadas cetesb", url: "/gerenciamento-areas-contaminadas-cetesb" },
    { title: "Gerenciamento de áreas contaminadas", url: "/gerenciamento-areas-contaminadas" },
    { title: "Homologação de pátio de madeira", url: "/homologacao-patio-madeira" },
    { title: "Laudo avcb preço", url: "/laudo-avcb-preco" },
    { title: "Laudo de Estanqueidade", url: "/laudo-estanqueidade" },
    { title: "Licença ambiental de ampliação", url: "/licenca-ambiental-ampliacao" },
    { title: "Licença ambiental da empresa", url: "/licenca-ambiental-da-empresa" },
    { title: "Licença ambiental fertilizante ribeirão preto", url: "/licenca-ambiental-fertilizante-ribeirao-preto" },
    { title: "Licença ambiental fertilizante em sp", url: "/licenca-ambiental-fertilizante-sp" },
    { title: "Licença Ambiental de Instalação e Operação", url: "/licenca-ambiental-instalacao-operacao" },
    { title: "Licença ambiental de operação", url: "/licenca-ambiental-operacao" },
    { title: "Licença ambiental para postos de combustível ribeirão preto", url: "/licenca-ambiental-postos-combustivel-ribeirao-preto" },
    { title: "Licença ambiental para postos de combustível em são paulo", url: "/licenca-ambiental-postos-combustivel-sao-paulo" },
    { title: "Licença ambiental para postos de combustível", url: "/licenca-ambiental-postos-combustivel" },
    { title: "Licenciamento ambiental garagem de ônibus em são paulo", url: "/licenciamento-ambiental-garagem-onibus-sao-paulo" },
    { title: "Outorga de água para irrigação", url: "/outorga-agua-irrigacao" },
    { title: "Outorga barramento", url: "/outorga-barramento" },
    { title: "Outorga para captação de água superficial", url: "/outorga-captacao-agua-superficial" },
    { title: "Outorga captação de água", url: "/outorga-captacao-agua" },
    { title: "Outorga para irrigação", url: "/outorga-irrigacao" },
    { title: "Outorga de poço preço", url: "/outorga-poco-preco" },
    { title: "Regularização ambiental posto de combustível ribeirão preto", url: "/regularizacao-ambiental-posto-combustivel-ribeirao-preto" },
    { title: "Regularização ambiental posto de combustível", url: "/regularizacao-ambiental-posto-combustivel" },
    { title: "Serviço de aprovação de corpo de bombeiro", url: "/servico-aprovacao-corpo-bombeiro" },
    { title: "Serviço de assessoria ambiental em ribeirão preto sp", url: "/servico-assessoria-ambiental-ribeirao-preto-sp" },
    { title: "Serviço de assessoria ambiental em ribeirão preto", url: "/servico-assessoria-ambiental-ribeirao-preto" },
    { title: "Serviço de consultoria ambiental para posto de combustível", url: "/servico-consultoria-ambiental-posto-combustivel" },
    { title: "Serviço de corte de árvore nativa isolada", url: "/servico-corte-arvore-nativa-isolada" },
    { title: "Serviço de outorga daee", url: "/servico-outorga-daee" },
    { title: "Serviço de regularização ambiental posto de combustível", url: "/servico-regularizacao-ambiental-posto-combustivel" },
    { title: "Serviço de regularização anp em ribeirão preto", url: "/servico-regularizacao-anp-ribeirao-preto" },
    { title: "Vistoria de bombeiro", url: "/vistoria-bombeiro" },
    { title: "Vistoria corpo de bombeiros sp", url: "/vistoria-corpo-bombeiros-sp" }
];